// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

import { useState, useEffect } from "react";
import { Nav } from "./components/Nav";
import { Hero } from "./components/Hero";
import { StagesBand } from "./components/StagesBand";
import { Architecture } from "./components/Architecture";
import { Sidebar } from "./components/Sidebar";
import { DeployingSidebar } from "./components/DeployingSidebar";
import { MarkdownPage } from "./components/MarkdownPage";
import { ApiReferenceSafe } from "./components/ApiReferenceSafe";
import { pages, type PageId } from "./pages";

type Tab = "home" | "deploying" | "how-it-works" | "api-reference";

function getTabFromHash(): { tab: Tab; page: PageId } {
  const hash = window.location.hash.replace("#/", "").replace("#", "");
  if (hash === "" || hash === "home") return { tab: "home", page: "deploying" };
  if (hash === "deploying") return { tab: "deploying", page: "deploying" };
  if (hash === "how-it-works") return { tab: "how-it-works", page: "sources" };
  if (hash === "api-reference")
    return { tab: "api-reference", page: "deploying" };
  if (hash in pages) return { tab: "how-it-works", page: hash as PageId };
  return { tab: "home", page: "deploying" };
}

export function App(): React.JSX.Element {
  const [state, setState] = useState(getTabFromHash);

  useEffect(() => {
    const onHash = () => setState(getTabFromHash());
    window.addEventListener("hashchange", onHash);
    return () => window.removeEventListener("hashchange", onHash);
  }, []);

  return (
    <div className="paper-grain min-h-screen">
      <Nav activeTab={state.tab} />
      {state.tab === "home" && (
        <>
          <Hero />
          <StagesBand />
          <Architecture />
        </>
      )}
      {state.tab === "deploying" && (
        <div className="mx-auto flex w-full max-w-7xl px-6 sm:px-10 lg:px-14">
          <DeployingSidebar />
          <main className="min-w-0 flex-1 py-8 pl-0 md:pl-12">
            <MarkdownPage content={pages.deploying} />
          </main>
        </div>
      )}
      {state.tab === "how-it-works" && (
        <div className="mx-auto flex w-full max-w-7xl px-6 sm:px-10 lg:px-14">
          <Sidebar currentPage={state.page} />
          <main className="min-w-0 flex-1 py-8 pl-0 md:pl-12">
            <MarkdownPage content={pages[state.page]} />
          </main>
        </div>
      )}
      {state.tab === "api-reference" && (
        <div className="mx-auto w-full max-w-7xl px-6 py-8 sm:px-10 lg:px-14">
          <ApiReferenceSafe />
        </div>
      )}
      <footer className="border-t border-rule">
        <div className="mx-auto w-full max-w-7xl px-6 py-8 text-[11px] leading-[1.6] text-ink-faint sm:px-10 lg:px-14">
          <p>
            The information on this site is for informational purposes only. AWS
            makes no warranties, express or implied, regarding the accuracy,
            completeness, or fitness for a particular purpose of any information
            or outputs generated by Context Ontology Accelerator. Use of Context
            Ontology Accelerator is governed by the AWS Customer Agreement and
            applicable AWS Service Terms. Customers are responsible for
            independently validating all outputs before relying on them for
            business, legal, or regulatory purposes.
          </p>
          <p className="mt-2">
            Context Ontology Accelerator's security features (Cedar
            authorization, SQL Firewall, PII guardrails) operate within the{" "}
            <a
              href="https://aws.amazon.com/compliance/shared-responsibility-model/"
              className="underline decoration-ink-faint/40 underline-offset-2 hover:decoration-ink-faint"
            >
              AWS Shared Responsibility Model
            </a>
            . Customers are responsible for configuring authorization policies,
            defining PII classifications, and maintaining data catalog accuracy;
            AWS is responsible for the security of the underlying cloud
            infrastructure.
          </p>
          <p className="mt-2">
            Your ontologies, mappings, SHACL shapes, and governed metrics remain
            Your Content. See the AWS Customer Agreement for complete terms
            governing your data and intellectual property.
          </p>
          <p className="mt-2">
            Context Ontology Accelerator is licensed under the Apache License
            2.0. For a complete list of open-source dependencies and their
            respective licenses, see the repository's NOTICE.md file.
          </p>
          <p className="mt-4 text-ink-muted">
            Copyright © 2026 Amazon Web Services, Inc. and/ or its affiliates.
            All rights reserved.
          </p>
        </div>
      </footer>
    </div>
  );
}
