# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

"""Class-level normalization via embedding similarity.

Given a set of distinct classification strings — each paired with the
LLM-generated description from
:mod:`coa_ontology.inducer.unstructured.services.description_generator`
— this module decides for each one whether to **reuse** an already-seen
class IRI (because cosine similarity is high enough) or to **mint** a
fresh IRI through the
:class:`~coa_ontology.inducer.unstructured.services.iri_resolver.IRIResolver`.

The decision is bucketed into three :class:`MatchBand` values:

- ``exact``       — cosine ≥ ``EXACT_THRESHOLD`` (default 0.95). The
  caller MUST reuse the matched IRI as-is. No new IRI is minted; the
  index is NOT updated for the class (the existing entry already
  represents this class).
- ``close_match`` — ``CLOSE_MATCH_THRESHOLD`` ≤ cosine < ``EXACT_THRESHOLD``
  (default 0.80 ≤ x < 0.95). A new IRI IS minted, the new (label,
  vector, IRI) tuple is added to the index, and the caller is
  expected to attach a ``skos:closeMatch`` link to the matched IRI when
  emitting Turtle (the link itself is asserted later in induction Rule 1
  / serializer; this module only records the existing IRI in the result).
- ``novel``       — cosine < ``CLOSE_MATCH_THRESHOLD``, OR the existing
  index is empty when the class is processed. A fresh IRI is minted,
  the new tuple is added to the index, and no SKOS link is recorded.

## First-class-wins semantics (T-Box)

The index is built **incrementally during the same** ``normalize()``
**call**. The first time a particular label/description appears it
gets minted (band=``novel``); subsequent inputs that hash near it
match it as ``exact`` or ``close_match``. This keeps the implementation
simple and avoids requiring a pre-flight embedding pass over the entire
class population — but it does mean that **iteration order matters
when several classes are very similar to one another**. Callers that
care about determinism should sort the input dict before calling
``normalize`` (Python 3.7+ ``dict`` preserves insertion order).

## Reusing an index across calls

Pass an :class:`InMemoryClassEmbeddingIndex` instance via the ``index``
keyword argument to share state across calls — useful when classes are
streamed in batches or when later phases of a pipeline want to align
new candidates against earlier ones. If ``index`` is ``None``, a fresh
empty index is created internally.

## Mode awareness

The description text fed in here may have been generated by any of the
modes implemented in
:mod:`coa_ontology.inducer.unstructured.services.description_generator`:

- ``none``     — label-only output (LLM uses parametric memory).
- ``instance`` — descriptions grounded in per-entity facts.
- ``schema``   — descriptions grounded in T-Box schema fingerprints
  (recommended for ontology rdfs:comment generation).

The embedding logic itself is mode-agnostic — what changes with mode is
the *content* of the description string. To make downstream reports
traceable, callers can pass ``source_mode`` to :func:`normalize` and the
returned :class:`NormalizationResult` records it. The normalizer never
branches on ``source_mode``.

## Backend notes

The normalizer ships with :class:`InMemoryClassEmbeddingIndex` — a
local linear-scan kNN over a list of ``(label, description, vector,
iri)`` tuples. This is appropriate for the populations the unstructured
induction pipeline targets (dozens to low hundreds of classes per
graph). For larger populations, swap in a persistent vector backend
that satisfies the same :class:`ClassEmbeddingIndex` Protocol — see
the OPTIONAL Task 10A.3 in tasks.md.

## Usage

::

    from coa_ontology.inducer.unstructured.services.class_normalizer import (
        InMemoryClassEmbeddingIndex,
        normalize,
    )

    descriptions = {
        "Company": "A Company is a business organization ...",
        "Person":  "A Person is an individual human being ...",
    }
    index = InMemoryClassEmbeddingIndex()        # optional; auto-created if omitted
    results = normalize(
        classes=descriptions,
        embedding_client=bedrock_client,         # has .embed_text(text)
        iri_resolver=resolver,                    # has .resolve(label, classification)
        index=index,
        source_mode="schema",
    )
    # results: {
    #   "Company": NormalizationResult(class_iri="http://...", band="novel", similarity_score=0.0, ...),
    #   "Person":  NormalizationResult(class_iri="http://...", band="novel", similarity_score=0.X, ...),
    # }
    # On a follow-up call with the same descriptions, every result will be
    # band="exact" and class_iri will reuse the IRI minted in the first call.
"""

from __future__ import annotations

import logging
import math
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Literal, Protocol

if TYPE_CHECKING:
    from coa_ontology.inducer.unstructured.services.iri_resolver import (
        IRIResolver,
    )

log = logging.getLogger(__name__)

# Cosine similarity thresholds for the three match bands. The defaults
# match Requirement 9 (acceptance criteria 9.3 / 9.4 / 9.5).
EXACT_THRESHOLD: float = 0.95
CLOSE_MATCH_THRESHOLD: float = 0.80


MatchBand = Literal["exact", "close_match", "novel"]


@dataclass
class NormalizationResult:
    """Outcome of normalizing a single classification string.

    Attributes:
        class_iri: The IRI the caller should use for this class. For the
            ``exact`` band this is the existing matched IRI; for
            ``close_match`` and ``novel`` it is a freshly-minted IRI.
        band: One of ``"exact"`` / ``"close_match"`` / ``"novel"``.
        similarity_score: The cosine similarity to the top-1 nearest
            existing class embedding, or ``0.0`` if the index was empty.
        matched_existing_iri: The IRI of the top-1 match when present —
            populated for the ``exact`` and ``close_match`` bands. ``None``
            for ``novel`` (per spec Req 9.5: novel is "no link to
            existing classes") and ``None`` when the index was empty
            when the class was processed.
        source_mode: A free-form string identifying which description-
            generator mode produced the input description (e.g.
            ``"none"`` / ``"instance"`` / ``"schema"`` / ``None``).
            Threaded through verbatim from the caller for traceability;
            the normalizer never branches on it.
    """

    class_iri: str
    band: MatchBand
    similarity_score: float
    matched_existing_iri: str | None = None
    source_mode: str | None = None


class ClassEmbeddingClient(Protocol):
    """Structural type for the embedding client used by ``normalize``.

    Any object exposing an ``embed_text(text) -> list[float]`` method
    satisfies this protocol. The existing
    :class:`~coa_ontology.bedrock_embeddings.BedrockEmbeddingClient`
    matches by definition.
    """

    def embed_text(self, text: str) -> list[float]:
        """Return the embedding vector for the given text."""
        ...


# ── In-memory class embedding index ─────────────────────────────────────


@dataclass
class _IndexEntry:
    """One label/description/IRI/vector tuple in the in-memory index."""

    label: str
    description: str
    vector: list[float]
    iri: str


@dataclass
class InMemoryClassEmbeddingIndex:
    """Growable in-memory kNN index for class embeddings.

    Holds ``(label, description, vector, IRI)`` tuples. Provides a
    linear-scan kNN-1 lookup that returns cosine similarity directly
    (no backend transformation required since we compute cosine here).

    The implementation assumes vectors are unit-length (the
    :class:`~coa_ontology.bedrock_embeddings.BedrockEmbeddingClient`
    requests ``"normalize": True`` from Bedrock Titan, which guarantees
    this). Under that invariant, cosine similarity reduces to a dot
    product, so kNN on a few hundred entries is microseconds.

    A small **embed-text cache** is maintained alongside the entries so
    repeat calls with identical ``"{label}: {description}"`` text don't
    re-call the embedding client. The cache is keyed by the embed text
    (after the trim/concatenation done by :func:`_build_embedding_text`).
    """

    entries: list[_IndexEntry] = field(default_factory=list)
    # Maps the canonical embed text to a cached vector. Populated by
    # ``normalize`` when it embeds; consulted by ``embed_or_cache``.
    embed_cache: dict[str, list[float]] = field(default_factory=dict)

    # ── Public surface ────────────────────────────────────────────────

    def __len__(self) -> int:
        """Return the number of entries currently in the index."""
        return len(self.entries)

    def add(
        self,
        label: str,
        description: str,
        vector: list[float],
        iri: str,
    ) -> None:
        """Append a new class entry to the index.

        Does NOT deduplicate. Callers that need exact-match deduplication
        should consult :meth:`top_k` first and act on the returned band.
        """
        self.entries.append(
            _IndexEntry(
                label=label,
                description=description,
                vector=vector,
                iri=iri,
            )
        )

    def top_k(self, vector: list[float], k: int = 1) -> list[tuple[float, _IndexEntry]]:
        """Return the top-``k`` nearest entries by cosine similarity.

        Uses dot product on the assumption that ``vector`` and all stored
        vectors are unit-length. Falls back to a defensive normalized
        cosine when a stored vector is not unit-length, so the function
        still returns correct values for non-normalized inputs at a
        small extra cost per pair.

        Returns:
            A list of ``(cosine_similarity, entry)`` tuples sorted by
            cosine descending. Empty when the index is empty.
        """
        if not self.entries or not vector:
            return []
        scored: list[tuple[float, _IndexEntry]] = []
        for entry in self.entries:
            if not entry.vector:
                continue
            scored.append((_cosine(vector, entry.vector), entry))
        scored.sort(key=lambda pair: pair[0], reverse=True)
        return scored[:k]


# ── Internals ───────────────────────────────────────────────────────────


def _build_embedding_text(label: str, description: str) -> str:
    """Produce the canonical input text for the embedding model.

    Per Requirement 9.8 the embedding is computed over both the class
    label AND the generated description, concatenated as
    ``"{label}: {description}"`` so semantically similar classes with
    different surface labels still match.

    A blank description is permitted (the embedding then reduces to
    just the label, which still produces a valid vector but loses the
    semantic boost from the description).

    Args:
        label: The class label (e.g. ``"Person"``).
        description: The generated rdfs:comment-style description.

    Returns:
        The text to be embedded.
    """
    description = description.strip() if description else ""
    if description:
        return f"{label}: {description}"
    return label


def _band_for_score(score: float) -> MatchBand:
    """Bucket a cosine similarity into one of the three match bands."""
    if score >= EXACT_THRESHOLD:
        return "exact"
    if score >= CLOSE_MATCH_THRESHOLD:
        return "close_match"
    return "novel"


def _cosine(a: list[float], b: list[float]) -> float:
    """Cosine similarity between two vectors, robust to non-unit norms.

    For unit-length vectors this reduces to a dot product. Falls back
    to explicit normalization when the inputs are not unit-length so a
    caller using non-Bedrock embeddings still gets correct values.

    Returns ``0.0`` for any malformed input (empty, mismatched length,
    or zero-norm vectors).
    """
    if not a or not b or len(a) != len(b):
        return 0.0
    dot = 0.0
    norm_a_sq = 0.0
    norm_b_sq = 0.0
    for x, y in zip(a, b, strict=True):
        dot += x * y
        norm_a_sq += x * x
        norm_b_sq += y * y
    if norm_a_sq <= 0.0 or norm_b_sq <= 0.0:
        return 0.0
    if abs(norm_a_sq - 1.0) < 1e-6 and abs(norm_b_sq - 1.0) < 1e-6:
        return dot
    return dot / (math.sqrt(norm_a_sq) * math.sqrt(norm_b_sq))


def _embed_with_cache(
    embedding_client: ClassEmbeddingClient,
    index: InMemoryClassEmbeddingIndex,
    text: str,
) -> list[float]:
    """Embed ``text``, consulting/populating the index's embed_cache.

    Saves a Bedrock round-trip when the same embedding text appears
    multiple times in a single ``normalize`` call (or across calls
    sharing the same index).
    """
    cached = index.embed_cache.get(text)
    if cached is not None:
        return cached
    vector = embedding_client.embed_text(text)
    index.embed_cache[text] = vector
    return vector


# ── Public API ──────────────────────────────────────────────────────────


def normalize(
    classes: dict[str, str],
    embedding_client: ClassEmbeddingClient,
    iri_resolver: IRIResolver,
    *,
    index: InMemoryClassEmbeddingIndex | None = None,
    source_mode: str | None = None,
) -> dict[str, NormalizationResult]:
    """Normalize each class label against the running embedding index.

    For each ``(label, description)`` pair, in iteration order:

    1. Build the embedding text via :func:`_build_embedding_text`.
    2. Embed it via ``embedding_client.embed_text`` (with caching).
    3. Run a top-1 cosine kNN against the running ``index``.
    4. Bucket the top hit into a :class:`MatchBand`.
    5. For ``exact``: reuse ``hit.iri``; do NOT add to the index.
       For ``close_match`` / ``novel``: mint a fresh IRI via
       ``iri_resolver.resolve(label, "class")`` (the literal ``"class"``
       token disambiguates T-Box class IRIs from A-Box individual IRIs;
       see Req 10.2) and add the new entry to the index so subsequent
       classes in the same call (or later calls sharing the index)
       can match against it.

    Per-class fault isolation: any exception from the embedding client
    or the IRI resolver is caught, logged at WARNING level, and the
    affected class is treated as ``novel`` with score ``0.0``. The
    affected entry is NOT added to the index (since we have no vector
    for it). Programmer errors (e.g. wrong types) propagate.

    Args:
        classes: Mapping from class label (e.g. ``"Person"``) to its
            generated description. Either may be empty.
        embedding_client: Object satisfying :class:`ClassEmbeddingClient`.
        iri_resolver: The
            :class:`~coa_ontology.inducer.unstructured.services.iri_resolver.IRIResolver`
            used to mint new IRIs for ``close_match`` / ``novel`` bands.
        index: An :class:`InMemoryClassEmbeddingIndex`, possibly already
            populated from prior calls. If ``None`` a fresh empty index
            is created and discarded after the call. **Pass an explicit
            instance to share state across calls.**
        source_mode: Free-form string identifying the description mode
            for downstream traceability. Common values:
            ``"none"`` / ``"instance"`` / ``"schema"`` / ``None``.

    Returns:
        Mapping from each input class label to a
        :class:`NormalizationResult`. Keys exactly match the input keys.
    """
    if index is None:
        index = InMemoryClassEmbeddingIndex()

    log.info(
        "Normalizing %d classes against in-memory index (initial size=%d, source_mode=%s)",
        len(classes),
        len(index),
        source_mode,
    )

    results: dict[str, NormalizationResult] = {}

    for label, description in classes.items():
        text = _build_embedding_text(label, description)
        log.debug(
            "Class %r: embedding %d-char text (index size=%d)",
            label,
            len(text),
            len(index),
        )

        # Embed.
        try:
            vector = _embed_with_cache(embedding_client, index, text)
        except Exception as exc:  # noqa: BLE001
            log.warning(
                "Embedding failed for class %r (%s: %s) — treating as novel without adding to index",
                label,
                type(exc).__name__,
                exc,
            )
            results[label] = _resolve_novel(
                label,
                iri_resolver,
                score=0.0,
                source_mode=source_mode,
                index_to_update=None,  # nothing to add — we have no vector
                description=description,
            )
            continue

        # Top-1 kNN against everything seen so far.
        hits = index.top_k(vector, k=1)
        if not hits:
            # Empty index: this class is novel by definition.
            log.debug("Class %r: index empty — novel (first class seen)", label)
            results[label] = _resolve_novel(
                label,
                iri_resolver,
                score=0.0,
                source_mode=source_mode,
                index_to_update=index,
                vector=vector,
                description=description,
            )
            continue

        score, top = hits[0]
        band = _band_for_score(score)
        matched_iri = top.iri or None
        log.debug(
            "Class %r: top match label=%r iri=%s score=%.4f band=%s",
            label,
            top.label,
            matched_iri,
            score,
            band,
        )

        if band == "exact":
            # Reuse the existing IRI. Do NOT add to the index — the
            # existing entry already represents this class.
            results[label] = NormalizationResult(
                class_iri=matched_iri or "",
                band="exact",
                similarity_score=score,
                matched_existing_iri=matched_iri,
                source_mode=source_mode,
            )
            continue

        # close_match (Req 9.4) or novel (Req 9.5): mint and add to index.
        try:
            # Per Req 10.2, class IRIs use the literal token ``"class"``
            # in the classification slot — distinguishes T-Box class IRIs
            # from A-Box individual IRIs that would otherwise collide
            # when an entity is literally named "Person" of class Person.
            class_iri = iri_resolver.resolve(label, "class")
        except Exception as exc:  # noqa: BLE001
            log.warning(
                "IRI resolver failed for class %r (%s: %s) — returning novel with empty class_iri",
                label,
                type(exc).__name__,
                exc,
            )
            results[label] = NormalizationResult(
                class_iri="",
                band="novel",
                similarity_score=0.0,
                matched_existing_iri=None,
                source_mode=source_mode,
            )
            continue

        # Add the new (label, vector, iri) to the index so subsequent
        # classes can match against it.
        index.add(
            label=label,
            description=description,
            vector=vector,
            iri=class_iri,
        )

        results[label] = NormalizationResult(
            class_iri=class_iri,
            band=band,
            similarity_score=score,
            # Per spec Req 9.5: novel = "no link to existing classes",
            # so we don't surface the matched_existing_iri there.
            matched_existing_iri=matched_iri if band == "close_match" else None,
            source_mode=source_mode,
        )

    log.info(
        "Normalization complete: final index size=%d (entries added this call=%d)",
        len(index),
        sum(1 for r in results.values() if r.band in ("close_match", "novel") and r.class_iri),
    )

    return results


def _resolve_novel(
    label: str,
    iri_resolver: IRIResolver,
    *,
    score: float,
    source_mode: str | None,
    index_to_update: InMemoryClassEmbeddingIndex | None,
    description: str = "",
    vector: list[float] | None = None,
) -> NormalizationResult:
    """Helper for the empty-index and embed-failure paths.

    Mints a fresh IRI and (if ``index_to_update`` is non-None and
    ``vector`` was provided) adds the new entry to the index. If the
    resolver itself fails, returns an empty class_iri so the caller
    can detect the hard failure.
    """
    try:
        # Per Req 10.2, class IRIs use the literal token ``"class"`` in
        # the classification slot.
        class_iri = iri_resolver.resolve(label, "class")
    except Exception as exc:  # noqa: BLE001
        log.warning(
            "IRI resolver failed during novel mint for class %r (%s: %s) — returning empty class_iri",
            label,
            type(exc).__name__,
            exc,
        )
        return NormalizationResult(
            class_iri="",
            band="novel",
            similarity_score=score,
            matched_existing_iri=None,
            source_mode=source_mode,
        )

    if index_to_update is not None and vector:
        index_to_update.add(
            label=label,
            description=description,
            vector=vector,
            iri=class_iri,
        )

    return NormalizationResult(
        class_iri=class_iri,
        band="novel",
        similarity_score=score,
        matched_existing_iri=None,
        source_mode=source_mode,
    )
